---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-app-spring
  name: demo-app-spring
spec:
  ports:
    - port: 80
      name: web
      protocol: TCP
      targetPort: 8080
  selector:
    app: demo-app-spring
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-spring
  labels:
    app: demo-app-spring
spec:
  selector:
    matchLabels:
      app: demo-app-spring
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-app-spring
    spec:
      containers:
        - name: demo-app-spring
          image: yourUser/yourRepoNameHere
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 5
          ports:
            - containerPort: 8080